apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPolicies
metadata:
  name: enforce-externalname-port-policy
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
  parameters: {}
